### ISSUE TITLE
Can't make it work properly in VS Code

### ISSUE THREAD

**Issue by deiteris** [aml-org/als#495] opened 2021-03-31 17:19 UTC
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ...**
    - [ ] bug report
    - [ ] feature request
    - [x] question
    - [ ] other

* **What is the current behavior?**

I was able to create a VS Code extension by following the VS Code ALS client tutorial. The extension works, but language server has several major issues:

1. There's an error when opening a RAML file for the first time. See error below.
2. Code actions, autocomplete, type hinting, goto type definition, snippets don't work. See error below.
3. When opening a tab with another file, then switching back to previous file, the language server stops responding to requests at some point (infinite load).

* **If the current behavior is a bug, please provide the minimal steps to reproduce on ALS**

* **Please provide stack traces/logs and the failing JSON rpc message if possible**

1. When opening a RAML file: https://pastebin.com/YdQ9LTNg
2. Any code action: https://pastebin.com/5SMuw10R

* **File being edited (API spec/AML Document)**

Happens with any RAML file.

* **What is the expected behavior?**

It's supposed to work?

* **What is the motivation/use case for changing the behavior? (for feature requests)**

* **Please tell us about your environment:**

    - ALS Version: Tested with 3.3.0-SNAPSHOT / 3.2.5 / 3.1.0
    - ALS Distribution: JVM
    - OS: Windows 10 20H2
    - VS Code version: Tested with 1.34.2, 1.54.3

* **Other information** (e.g. detailed explanation, stack traces, related issues, workarounds, links for us to have context, eg. StackOverflow, Gitter, etc)

Here's the source ([client.zip](https://github.com/aml-org/als/files/6238278/client.zip)) of the VS Code client that I made based on tutorial. Just change the path to jar and open it in VS Code Extension Development environment. Please advise if I am doing something wrong or you need additional info.

**Comment by llibarona** [comment] 2021-03-31 19:06
Hi @deiteris 
could you provide the test file for which this error occurs?
I am using your extension in my local environment with `ALS 3.2.5` and there is no apparent error (which would indicate the extension is well built)

I'll attach a gif so you can tell me if there is anything different in my procedure
![test-gh-495](https://user-images.githubusercontent.com/45210281/113194432-852b5c00-9237-11eb-9b4d-3ab79a1749bc.gif)

Due to the current COVID situation, I cannot replicate the Windows OS environment at the moment (we will run further tests as soon as we set up this environment), so that is still a primary suspect.

According to `https://docs.microsoft.com/en-us/archive/blogs/ie/file-uris-in-windows` the expected URI for the file path in Windows should follow `file:///c:/path/to/the%20file.txt` shape (in contrast to the `file:///c%3A...` that seems to be being requested in the communication trace). Would you be able to do a quick check to see if changing this solves your problem? (If so, we will see to update this specific case in our documentation)

**Comment by agusayerza** [comment] 2021-03-31 19:54
Hey there, I was able to reproduce the bug on a Windows environment. It does seem OS related, probably due to how file URIs are treated.

**Comment by deiteris** [comment] 2021-03-31 20:07
>According to https://docs.microsoft.com/en-us/archive/blogs/ie/file-uris-in-windows the expected URI for the file path in Windows should follow file:///c:/path/to/the%20file.txt shape (in contrast to the file:///c%3A... that seems to be being requested in the communication trace). Would you be able to do a quick check to see if changing this solves your problem? (If so, we will see to update this specific case in our documentation)
Here is a link to a known issue with Windows URIs on VSCode, and a patch: microsoft/vscode-languageserver-node#105

Ok, this pointed me in right direction and I've managed to fix it, and now it's possible to work with it. Here's the code that I used for the `./src/extension.ts`: https://pastebin.com/BPu5uGwT

However:
>I'll attach a gif so you can tell me if there is anything different in my procedure

1. I don't have such snippets and autocompletion available for some reason and there are no errors: https://imgur.com/Q3lsEZy
2. There's the same error (as the one, when I'm opening a RAML file) when I am selecting a range (it can be also seen in p.1 gif) or moving the cursor to the beginning of the link to a library. Here's the stacktrace: https://pastebin.com/JXAhsFUx
3. The strange issue with language server being stuck at some point is still there (maybe due to the error occurring in p. 2?): https://imgur.com/wYdXcfc

**Comment by deiteris** [comment] 2021-03-31 20:43
Here's the full trace: https://pastebin.com/LrdLTGDJ

>Is it possible you have more than one extension associated to the file? there seem to be some validations that are not coming from ALS.
No, this is the only extension, that is associated with the `.raml` file extension. The other validation comes from Code Spell Checker that simply check grammar. I've disabled it, but nothing changed, unfortunately.
![image](https://user-images.githubusercontent.com/6103913/113208502-89c53400-927a-11eb-96c9-873033e69600.png)

**Comment by llibarona** [comment] 2021-03-31 21:27
OK, there seems to be a bug on our side, when receiving the Context (with some Diagnostics), we expect the `code` property, which is optional, so we fail unexpectedly.
I drafted a solution in
> https://github.com/aml-org/als/tree/github-495/test-fix

which you can test
In case this works for you, we will see to update our code accordingly, if not we will still create an internal ticket to solve this problem

**Comment by llibarona** [comment] 2021-03-31 22:25
> UPD.: Nvm, ctrl+space shows suggestions as intended. Looks like it's just my VS Code settings.

Splendid! Do snippets also work fine with this? (Snippets are usually allocated at the bottom of the suggestion list)

Regarding the language server stoping for no apparent reason, don't hesitate to create a ticket with the stacktrace, file and steps (or at least approximately) and we will try to find out the reason.

**Comment by llibarona** [comment] 2021-04-01 16:15
> Yeah, snippets are also there, and the option for vs code is editor.quickSuggestions, that helps with autocomplete and suggestions.

Great news!

> Right now I have a quick workaround, that restarts the client when this issue occurs. I simply stop-start client with registered command like that and this probably should help for the time being:

Great that you could workaround this issue, we will try and detect/fix it so in the future this won't be necessary!

> This issue probably can be closed, but just one small question: is there any documentation on available language server options?

Yes, we have our implemented features in the readme file for github (https://github.com/aml-org/als#currently-supported-lsp-features)
And each feature has relevant info of it's own (for example `https://github.com/aml-org/als/blob/develop/documentation/features/custom-messages.md` contains messages we implemented that are not specified in the protocol)

For a more concrete example, you have a configuration message by which you can enable/disable template snippets in completion: `https://github.com/aml-org/als/blob/develop/documentation/features/custom-messages.md#updateconfiguration`

I think we missed a few relevant messages (for example the initialisation message, in which we accept some customisation for the server). We will see to update this (and please feel free to mention any particular options you think could use documentation)

**Comment by deiteris** [comment] 2021-04-01 20:47
>Great that you could workaround this issue, we will try and detect/fix it so in the future this won't be necessary!

Looking forward to this fix :)

>For a more concrete example, you have a configuration message by which you can enable/disable template snippets in completion: https://github.com/aml-org/als/blob/develop/documentation/features/custom-messages.md#updateconfiguration

But what will be the configuration property for that? F.e., for trace it's `trace.server`, but what it will be for `templateType`?

Also, there's another issue that I've just noticed. When I'm opening a RAML file in **Source Control**, I am getting this error: https://pastebin.com/nbeX7TUZ

**Comment by llibarona** [comment] 2021-04-01 21:06
> But what will be the configuration property for that? F.e., for `trace` it's trace.server, but what it will be for templateType?

I'm not sure I understand, here is a an expected configuration request:
```
[Trace - 5:56:47 PM] Sending notification 'updateConfiguration'.
Params: {
    "formattingOptions": {
        "application/raml+yaml": {
            "tabSize": 4,
            "preferSpaces": true
        },
        "application/yaml": {
            "tabSize": 4,
            "preferSpaces": true
        },
        "application/json": {
            "tabSize": 4,
            "preferSpaces": true
        }
    },
    "templateType": "FULL"
}
```

And an example for RenameFile trace:

```
[Trace - 6:00:33 PM] Sending request 'renameFile - (7)'.
Params: {
    "oldDocument": {
        "uri": "file:///Users/llibarona/Desktop/apis/raml/test02/api.raml"
    },
    "newDocument": {
        "uri": "file:///Users/llibarona/Desktop/apis/raml/test02/api2.raml"
    }
}
```

Is this any help?

> Also, there's another issue that I've just noticed. When I'm opening a RAML file in Source Control, I am getting this error: https://pastebin.com/nbeX7TUZ

This seems to be related  to the unexpected URI (similar to the first problem), we will create an internal ticket to solve this issue.
Does this occur in every case? or with a specific workspace/file distribution?
If you could facilitate a full trace that would be helpful (so we can see initialisation/open/change messages)

**Comment by deiteris** [comment] 2021-04-01 21:40
>Is this any help?

Yeah, well, I'm not too familiar with the VS Code extension API, but I think I've got the idea. At least in these examples I see that `updateConfiguration` is a notification and I can use the `sendNotification()` method (apparently).

>Does this occur in every case? or with a specific workspace/file distribution?
If you could facilitate a full trace that would be helpful (so we can see initialisation/open/change messages)

This happens in every case. When I open a file in Source Control, and also when I am trying to hover over anything in old changes. And it indeed looks like there's a problem with URI for the old changes, here's the full trace: https://pastebin.com/7Xqd8WNg

**Comment by llibarona** [comment] 2021-04-05 12:59
> Yeah, well, I'm not too familiar with the VS Code extension API, but I think I've got the idea. At least in these examples I see that updateConfiguration is a notification and I can use the client.sendNotification() method (apparently).

Yes, exactly, every custom message is registered at start, either adding as a command (example: `vscode.commands.registerCommand("als.renameFile", renameFileHandler)`) or in this case, as a callback for configuration change (example: `workspace.onDidChangeConfiguration(() => notifyConfig(languageClient))`) with `notifyConfig(languageClient)` doing `languageClient.sendNotification(messages.AlsConfigurationNotification.type, currentConfiguration)` 


> This happens in every case. When I open a file in Source Control, and also when I am trying to hover over anything in old changes in diff window. And it indeed looks like there's a problem with URI for the old changes, here's the full trace: https://pastebin.com/7Xqd8WNg

Indeed this seems to be URI-related, we will take a deeper look to see what we can do about it, thanks for the log!

**Comment by deiteris** [comment] 2021-04-09 12:59
Hi @llibarona. I've been observing the issue with language server stopping responding, and here are my thoughts on the issue: the issue mainly happens when actively typing and using autocomplete feature, so I assume that there're too many requests coming through the socket and it causes misbehavior. Unfortunately, even if I use my command to restart the extension, it stops working at this point too, only "Developer: Reload Window" actually helps. So my best guess is that typing should be throttled or delayed somehow by server or client to prevent this kind of behavior.

I wanted to send a trace to the point, when language client starts sending only `$/cancelRequest` notifications (this is when the language server stops responding), but in under 2 minutes I've managed make it stop responding and generated almost 1mb (!) of trace logs with empty document, and the pastebin limit is 512kb.

**Comment by llibarona** [comment] 2021-04-09 13:14
Hi @deiteris, 
That's a lot of logs! maybe you can uploaded as a `zip` so we can take a look.
For visibility purposes, would you mind creating a new ticket specifically for this?
If so, I close this current ticket and if someone else has the same problem it's easier to find!

**Comment by deiteris** [comment] 2021-04-09 13:22
Yes, sure, this issue can be closed, I'll create a new one. Just don't forget to include the 7afcb36a0314b8d7cc11dfeef4f1c9f2555ee140 fix in the next release :)

**Closed** 2021-04-09 13:22 UTC

**Comment by llibarona** [comment] 2021-04-09 13:26
For sure! the fix should be in `develop` shortly 😄
